---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helloworld-tf-dev
spec:
  interval: 1m
  url: https://github.com/dginther/tf-controller
  ref:
    branch: dev
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
  namespace: flux-system
spec:
  path: ./terraform
  approvePlan: "auto"
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helloworld-tf-dev
  varsFrom:
    - kind: Secret
      name: aws-credentials

